language: node_js
node_js: node
cache:
    directories:
        - node_modules
        - bower_components
services:
    - docker
branches:
  only:
  - master
script:
    - npm run pack
    - ls -l && ls -l dist
